[cash]
location = "local"

[mkfs]
location = "local"

[zeros]
location = "local"

[fatLib]
location = "local"

[regedit]
location = "local"

[log]
location = "local"

[toml]
location = "local"

[kernel]
location = "local"

[require]
location = "local"
